# Node.js with Ionic
# Build an Ionic project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @ionic/cli@<version_deseada>
    npm install
    ionic build --prod
  displayName: 'npm install and build'

- script: echo 'Show Ionic version and environment info' && ionic info
  displayName: 'Show Ionic version and environment info'
